# Generated by Django 5.2.4 on 2025-08-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawFacilityDim",
            fields=[
                ("facility_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("org_id", models.CharField(max_length=255)),
                ("boundary_conditions_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RawMaterialDim",
            fields=[
                ("material_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("blend_ratio", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=255)),
                ("certifications", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RawProcessStageDim",
            fields=[
                ("stage_id", models.AutoField(primary_key=True, serialize=False)),
                ("stage_name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RawRegistrySourceDim",
            fields=[
                ("registry_id", models.AutoField(primary_key=True, serialize=False)),
                ("registry_name", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=100)),
                ("ruleset", models.CharField(max_length=255)),
                ("api_endpoint", models.URLField()),
                ("last_sync_time", models.DateTimeField(blank=True, null=True)),
                ("registry_payload_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RawTextileProcessDim",
            fields=[
                ("process_id", models.AutoField(primary_key=True, serialize=False)),
                ("process_name", models.CharField(max_length=255)),
                ("stage", models.CharField(max_length=100)),
                ("energy_type", models.CharField(max_length=100)),
                ("unit_of_measurement", models.CharField(max_length=100)),
                ("details_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RawUnitMappingDim",
            fields=[
                ("mapping_id", models.AutoField(primary_key=True, serialize=False)),
                ("custom_unit", models.CharField(max_length=100)),
                ("kg_equivalent", models.FloatField()),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RawUserDim",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("org_id", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=100)),
                ("settings_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RawInputGSheetFact",
            fields=[
                (
                    "sheet_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("source_url", models.URLField()),
                ("import_timestamp", models.DateTimeField()),
                ("row_hash", models.CharField(max_length=255)),
                ("stage", models.CharField(max_length=100)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawInputNIRFact",
            fields=[
                (
                    "scanner_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("scan_time", models.DateTimeField()),
                ("composition_json", models.JSONField()),
                ("stage", models.CharField(max_length=100)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawInputRFIDFact",
            fields=[
                (
                    "tag_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("batch_id", models.CharField(max_length=255)),
                ("scan_time", models.DateTimeField()),
                ("context_json", models.JSONField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawLocationStageDim",
            fields=[
                (
                    "location_stage_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("stage_name", models.CharField(max_length=255)),
                ("estimated_transit_time_to_next", models.DurationField()),
                ("is_dispath_ready", models.BooleanField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawMarketplaceListingFact",
            fields=[
                ("listing_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                ("status", models.CharField(max_length=100)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawMaterialUploadFact",
            fields=[
                ("upload_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("source_type", models.CharField(max_length=100)),
                ("upload_time", models.DateTimeField()),
                ("stage", models.CharField(max_length=100)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawNirDeviceDim",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("location_metadata_json", models.JSONField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawProductLinkFact",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=255)),
                ("SKU", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("quantity_output_kg", models.FloatField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialuploadfact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawFacilityProcessMapFact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("default_energy_source", models.CharField(max_length=100)),
                ("active_from", models.DateField()),
                ("active_to", models.DateField(blank=True, null=True)),
                ("scope_flag", models.CharField(max_length=100)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawtextileprocessdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawEmissionFactorDim",
            fields=[
                ("factor_id", models.AutoField(primary_key=True, serialize=False)),
                ("material_type", models.CharField(max_length=100)),
                ("factor_value", models.FloatField()),
                ("source", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=100)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawtextileprocessdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawOrderSubmissionFact",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("material_ids", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                ("quantity_kg", models.FloatField()),
                ("unit_mapping_json", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawuserdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawInputManualFact",
            fields=[
                ("input_id", models.AutoField(primary_key=True, serialize=False)),
                ("stage", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("values_json", models.JSONField()),
                ("source_type", models.CharField(max_length=100)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawuserdim",
                    ),
                ),
            ],
        ),
    ]
