# Generated by Django 5.2.4 on 2025-08-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("raw_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcProofOfGoodFact",
            fields=[
                ("proof_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("verifier_id", models.CharField(max_length=255)),
                ("source_batch", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("proof_doc_url", models.URLField()),
                ("methodology_ref", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProcTraceChainFact",
            fields=[
                ("trace_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                (
                    "prev_step_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_step_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField()),
                ("hash", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProcEmissionsCalcFact",
            fields=[
                ("calc_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("activity_type", models.CharField(max_length=100)),
                ("emissions_kgco2", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawemissionfactordim",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawtextileprocessdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcInventoryFact",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("quantity_kg", models.FloatField()),
                ("custom_unit", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
                (
                    "unit_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawunitmappingdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcMarketplaceStateFact",
            fields=[
                ("state_id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process_data.procinventoryfact",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmarketplacelistingfact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcOrderFulfillmentFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_required_kg", models.FloatField()),
                ("quantity_matched_kg", models.FloatField()),
                ("order_fulfillment_status", models.CharField(max_length=100)),
                ("risk_reason", models.CharField(blank=True, max_length=255)),
                ("stock_status", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmarketplacelistingfact",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawordersubmissionfact",
                    ),
                ),
            ],
        ),
    ]
