# Generated by Django 5.2.4 on 2025-08-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("process_data", "0001_initial"),
        ("raw_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutAuditReportDim",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("report_type", models.CharField(max_length=100)),
                ("generation_date", models.DateField()),
                ("linked_cert_ids", models.JSONField()),
                ("reviewer_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OutBlockchainCommitLog",
            fields=[
                ("commit_id", models.AutoField(primary_key=True, serialize=False)),
                ("linked_table", models.CharField(max_length=255)),
                ("linked_id", models.CharField(max_length=255)),
                ("hash", models.CharField(max_length=255)),
                ("tx_hash", models.CharField(max_length=255)),
                ("commit_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OutCertificateIssueLogFact",
            fields=[
                ("cert_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("cert_type", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("verifier_id", models.CharField(max_length=255)),
                ("zk_hash", models.CharField(max_length=255)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutCreditGrantLogFact",
            fields=[
                ("credit_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("carbon_tonnes", models.FloatField()),
                ("price", models.FloatField()),
                ("methodology_ref", models.CharField(max_length=255)),
                ("grant_date", models.DateField()),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="output_data.outcertificateissuelogfact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutInventoryTraceFact",
            fields=[
                ("trace_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("path_hash", models.CharField(max_length=255)),
                ("cert_refs", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                ("stage", models.CharField(max_length=100)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawfacilitydim",
                    ),
                ),
                (
                    "location_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawlocationstagedim",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raw_data.rawmaterialdim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutMarketplaceActiveListingFact",
            fields=[
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="raw_data.rawmarketplacelistingfact",
                    ),
                ),
                ("current_status", models.CharField(max_length=100)),
                ("offer_price", models.FloatField()),
                ("buyer_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process_data.procinventoryfact",
                    ),
                ),
            ],
        ),
    ]
